version: "3.9"

services:
    api:
        container_name: api
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        image: ${DOMAIN}-api:latest
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - DB_HOST=mongodb
        env_file:
            - .env
        depends_on:
            - mongodb
        ports:
            - "3333:3333"
        networks:
            - api
            - mongo

    mongodb:
        container_name: mongodb
        image: mongo:5.0
        restart: unless-stopped
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - mongo

networks:
    api:
        internal: false
        driver: bridge

    mongo:
        internal: false
