version: "3.9"

services:
    api:
        container_name: api
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        image: ${DOMAIN}-api:latest
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - DB_NAME="/home/node/api/zk-groups.db"
        volumes:
            - sqlite:/home/node/api/zk-groups.db
        ports:
            - "3333:3333"
        networks:
            - zk-groups

    client:
        container_name: client
        build:
            context: ./
            dockerfile: ./apps/client/Dockerfile
        image: ${DOMAIN}-client:latest
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        ports:
            - "3002:80"
        networks:
            - zk-groups

    dashboard:
        container_name: dashboard
        build:
            context: ./
            dockerfile: ./apps/dashboard/Dockerfile
        image: ${DOMAIN}-dashboard:latest
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        ports:
            - "3001:80"
        networks:
            - zk-groups

networks:
    zk-groups:
        internal: false
        driver: bridge

volumes:
    sqlite:
