version: "3.9"

services:
    api:
        container_name: api
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        image: zk-groups-api:latest
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - DB_TYPE=postgres
            - DB_URL=
            - JWT_SECRET_KEY=
            - GITHUB_CLIENT_ID=
            - GITHUB_CLIENT_SECRET=
            - TWITTER_CONSUMER_KEY=
            - TWITTER_CONSUMER_SECRET=
            - REDDIT_CLIENT_ID=
            - REDDIT_CLIENT_SECRET=
            - NX_DEFAULT_NETWORK=localhost
            - NX_API_URL=http://localhost:3000/api
            - NX_DASHBOARD_URL=http://localhost:3001
            - BACKEND_PRIVATE_KEY=
            - INFURA_API_KEY=
        ports:
            - "3000:3000"
        networks:
            - zk-groups

    client:
        container_name: client
        build:
            context: ./
            dockerfile: ./apps/client/Dockerfile
        image: zk-groups-client:latest
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        ports:
            - "3002:80"
        networks:
            - zk-groups
        depends_on:
            - api

    dashboard:
        container_name: dashboard
        build:
            context: ./
            dockerfile: ./apps/dashboard/Dockerfile
        image: zk-groups-dashboard:latest
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        ports:
            - "3001:80"
        networks:
            - zk-groups
        depends_on:
            - api

#    postgres:
#         container_name: postgres
#         image: postgres
#         environment:
#             POSTGRES_USER: root
#             POSTGRES_PASSWORD: helloworld
#             POSTGRES_DB: zk-groups
#             PGDATA: /data/postgres
#         volumes:
#             - postgres:/data/postgres
#             - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
#         ports:
#             - "5432:5432"
#         restart: unless-stopped
#         command: postgres -c listen_addresses='*'
#         networks:
#             - zk-groups

networks:
    zk-groups:
        internal: false
        driver: bridge

volumes:
    postgres:
