name: Deploy
on:
  push:
  #  branches: [ master ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::490752553772:role/zkgroups-deploy-slc
          role-duration-seconds: 1800
          aws-region: eu-central-1

      - name: Build and Push images to ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 490752553772.dkr.ecr.eu-central-1.amazonaws.com

          docker build -t zk-groups-api:latest -f apps/api/Dockerfile .
          docker tag zk-groups-api:latest 490752553772.dkr.ecr.eu-central-1.amazonaws.com/zk-groups-api:latest
          docker push 490752553772.dkr.ecr.eu-central-1.amazonaws.com/zk-groups-api:latest

          docker build -t zk-groups-client:latest -f apps/client/Dockerfile .
          docker tag zk-groups-client:latest 490752553772.dkr.ecr.eu-central-1.amazonaws.com/zk-groups-client:latest
          docker push 490752553772.dkr.ecr.eu-central-1.amazonaws.com/zk-groups-client:latest

          docker build -t zk-groups-dashboard:latest -f apps/dashboard/Dockerfile .
          docker tag zk-groups-dashboard:latest 490752553772.dkr.ecr.eu-central-1.amazonaws.com/zk-groups-dashboard:latest
          docker push 490752553772.dkr.ecr.eu-central-1.amazonaws.com/zk-groups-dashboard:latest

      - name: Create Deployment
        run: |
          .github/scripts/deploy.sh
